"""initial tables

Revision ID: 0aad3c8d4a1d
Revises: 
Create Date: 2025-12-11 22:06:56.018856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aad3c8d4a1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('spades_A', sa.Boolean(), nullable=True),
    sa.Column('spades_2', sa.Boolean(), nullable=True),
    sa.Column('spades_3', sa.Boolean(), nullable=True),
    sa.Column('spades_4', sa.Boolean(), nullable=True),
    sa.Column('spades_5', sa.Boolean(), nullable=True),
    sa.Column('spades_6', sa.Boolean(), nullable=True),
    sa.Column('spades_7', sa.Boolean(), nullable=True),
    sa.Column('spades_8', sa.Boolean(), nullable=True),
    sa.Column('spades_9', sa.Boolean(), nullable=True),
    sa.Column('spades_10', sa.Boolean(), nullable=True),
    sa.Column('hearts_A', sa.Boolean(), nullable=True),
    sa.Column('hearts_2', sa.Boolean(), nullable=True),
    sa.Column('hearts_3', sa.Boolean(), nullable=True),
    sa.Column('hearts_4', sa.Boolean(), nullable=True),
    sa.Column('hearts_5', sa.Boolean(), nullable=True),
    sa.Column('hearts_6', sa.Boolean(), nullable=True),
    sa.Column('hearts_7', sa.Boolean(), nullable=True),
    sa.Column('hearts_8', sa.Boolean(), nullable=True),
    sa.Column('hearts_9', sa.Boolean(), nullable=True),
    sa.Column('hearts_10', sa.Boolean(), nullable=True),
    sa.Column('diamonds_A', sa.Boolean(), nullable=True),
    sa.Column('diamonds_2', sa.Boolean(), nullable=True),
    sa.Column('diamonds_3', sa.Boolean(), nullable=True),
    sa.Column('diamonds_4', sa.Boolean(), nullable=True),
    sa.Column('diamonds_5', sa.Boolean(), nullable=True),
    sa.Column('diamonds_6', sa.Boolean(), nullable=True),
    sa.Column('diamonds_7', sa.Boolean(), nullable=True),
    sa.Column('diamonds_8', sa.Boolean(), nullable=True),
    sa.Column('diamonds_9', sa.Boolean(), nullable=True),
    sa.Column('diamonds_10', sa.Boolean(), nullable=True),
    sa.Column('clubs_A', sa.Boolean(), nullable=True),
    sa.Column('clubs_2', sa.Boolean(), nullable=True),
    sa.Column('clubs_3', sa.Boolean(), nullable=True),
    sa.Column('clubs_4', sa.Boolean(), nullable=True),
    sa.Column('clubs_5', sa.Boolean(), nullable=True),
    sa.Column('clubs_6', sa.Boolean(), nullable=True),
    sa.Column('clubs_7', sa.Boolean(), nullable=True),
    sa.Column('clubs_8', sa.Boolean(), nullable=True),
    sa.Column('clubs_9', sa.Boolean(), nullable=True),
    sa.Column('clubs_10', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_progress')
    op.drop_table('user')
    # ### end Alembic commands ###
