"""add face cards and story progress

Revision ID: 54b18e5fccda
Revises: 0aad3c8d4a1d
Create Date: 2026-06-16 20:50:03.199374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b18e5fccda'
down_revision = '0aad3c8d4a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spades_J', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spades_Q', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spades_K', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hearts_J', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hearts_Q', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hearts_K', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diamonds_J', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diamonds_Q', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diamonds_K', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clubs_J', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clubs_Q', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clubs_K', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('story_choices', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_retries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_chapter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_progress', schema=None) as batch_op:
        batch_op.drop_column('current_chapter')
        batch_op.drop_column('total_retries')
        batch_op.drop_column('story_choices')
        batch_op.drop_column('clubs_K')
        batch_op.drop_column('clubs_Q')
        batch_op.drop_column('clubs_J')
        batch_op.drop_column('diamonds_K')
        batch_op.drop_column('diamonds_Q')
        batch_op.drop_column('diamonds_J')
        batch_op.drop_column('hearts_K')
        batch_op.drop_column('hearts_Q')
        batch_op.drop_column('hearts_J')
        batch_op.drop_column('spades_K')
        batch_op.drop_column('spades_Q')
        batch_op.drop_column('spades_J')

    # ### end Alembic commands ###
